### PR TITLE
add face detect example page

### PR DESCRIPTION
**Pull request by liyoung1992**

### CODE REVIEW

**Comment by liyoung1992** [comment]
Hi,@azihsoyn and @RichiWebever,
this push is baesd on [webeverde](https://github.com/webeverde/flutter_mlkit.git)

**Comment by azihsoyn** [comment]
Thank you for contributing!

**Comment by azihsoyn** [comment]
Hi, @liyoung1992!

The base branch has merged.

Please merge master and resolve conflict.

**Comment by azihsoyn** [comment]
@liyoung1992 

Thanks for the good example page and sorry late response.

:lgtm: 😄

**Pull request merged**
