### PR TITLE
Add feature to detect from binary

### PR DESCRIPTION
**Pull request by defned**
I made this PR to extend the interface with a detectFromBinary function to detect from an image directly.

### CODE REVIEW

**Comment by azihsoyn** [comment]
Thank you for contributing!

**Comment by azihsoyn** [comment]
Probably it takes a while to review.

**Comment by defned** [comment]
How can I help to make this process faster?

**Comment by azihsoyn** [comment]
Maybe nothing. Today I'll go home with the drunk.😋
I'm going to finish the review this week.

**Comment by azihsoyn** [comment]
Hi, @defned !
This is perfect PR! LGTM!

Please add a CHANGELOG.md entry and give the package version a bump to 0.5.0 in pubspec.yaml.

**Comment by azihsoyn** [comment]
👍

**Comment by azihsoyn** [comment]
I published 0.5.0.
https://pub.dartlang.org/packages/mlkit

Thanks!

**Pull request merged**
