### PR TITLE
Fixes `FIRAnalyticsVersionMismatch` compilation error on iOS.

### PR DESCRIPTION
**Pull request by thomas-stockx**
Similar to this PR in the official repo: https://github.com/flutter/plugins/pull/1213/files

### CODE REVIEW

**Comment by azihsoyn** [comment]
Hi, @thomas-stockx !

Thanks PR!

Please bump up version to 0.10.1 and edit change log.
- https://github.com/azihsoyn/flutter_mlkit/blob/master/pubspec.yaml#L3
- https://github.com/azihsoyn/flutter_mlkit/blob/master/CHANGELOG.md

**Comment by thomas-stockx** [comment]
> Hi, @thomas-stockx !
> 
> Thanks PR!
> 
> Please bump up version to 0.10.1 and edit change log.
> 
> * https://github.com/azihsoyn/flutter_mlkit/blob/master/pubspec.yaml#L3
> * https://github.com/azihsoyn/flutter_mlkit/blob/master/CHANGELOG.md

Done!

**Comment by azihsoyn** [comment]
Great!

:lgtm:

**Comment by azihsoyn** [comment]
I published mlkit@0.10.1.

https://pub.dartlang.org/packages/mlkit

Thanks to contributing! 😁

**Pull request merged**
